### ISSUE TITLE
[Bug] destroyService bumblebee bbWebsocketClient:localhost:37688

### ISSUE THREAD

**Issue by rafaelmateusm** [jaxcore/bumblebee#1]
I followed the guide and create the helloworld.js file
but as soon as I run it it gives me the following error:
```

destroyService bumblebee bbWebsocketClient:localhost:37688
connectApplication error: { timeout: true }

```

Is that normal? I am I missing something?

**Comment by rafaelmateusm** [comment]
Solved haha.

**Comment by dsteinman** [comment]
No problem.  You'll probably see errors like this especially if you stop and restart the app.  An app typically needs to be restarted twice at the moment.

**Comment by spwashi** [comment]
I haven't been able to get past this, where should I be looking?
I tried modifying `BumblebeeWebsocketClient` per https://github.com/socketio/socket.io-client/issues/1097#issuecomment-301301030 but that only got me to a 503 error

**Comment by dsteinman** [comment]
> I haven't been able to get past this, where should I be looking?
> I tried modifying `BumblebeeWebsocketClient` per [socketio/socket.io-client#1097 (comment)](https://github.com/socketio/socket.io-client/issues/1097#issuecomment-301301030) but that only got me to a 503 error

This error just means the socket.io client wasn't able to connect to the websocket.io server that's running in the bumblebee electron app (port 37688). 

One way to confirm the websocket server is running is to go to:

http://localhost:37688/

And it should print "bumblebee".  If it doesn't, then something is blocking port 37688.

**Comment by spwashi** [comment]
Oh, of course. Guess it'd be pretty hard to connect to a server that isn't running, huh. Now it's running perfectly!

Can you add that as a step to the Hello World example?

**Comment by dsteinman** [comment]
> Can you add that as a step to the Hello World example?

Certainly.  I guess yeah it's maybe not clear enough that all the examples are clients, and the electron app is the server which needs to be running.

Be sure to try all the nodejs-examples while you're at it (the web examples still need some work).   And please let me know what you think of this project and the idea.

**Comment by spwashi** [comment]
Sure thing! I'll be poking through them this week

**Comment by LingleDev** [comment]
I still get this error.

**Comment by LingleDev** [comment]
Scratch that. I read the electron-app bit
