### ISSUE TITLE
Is DeepSpeech 0.8.0 supported?

### ISSUE THREAD

**Issue by Patronics** [jaxcore/bumblebee#2]
Does or can this be made to support DeepSpeech 0.8.0? I used symlinks for the electron-app example to deepspeech-0.8.0-models.pbmm (and .scorer), but it seemed not to recognize them, and downloaded 0.7.4 anyway. Is this the intended behavior?

This seems perfect for my project, thanks for making it!

**Comment by dsteinman** [comment]
Yup, use the "dev" branch.  DeepSpeech 0.8 seems to work a bit better. 

Can I ask, did you use the packaged release or did you do a git clone and use the source?  I might just skip doing packaged releases going forward.

**Comment by dsteinman** [comment]
FYI I've merged that to master.

**Comment by Patronics** [comment]
Yeah, I used git clone. Thanks!
